### ISSUE TITLE
Token expiration causes Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by pitkes22** [saleor/auth-sdk#11]
There is a critical problem with refreshing the token. When you allow the token to expire, any attempt to make a request will cause the token to refresh. My assumption is that the request to the `refreshToken` also triggers this refresh, creating an infinite loop.

**Steps to reproduce (I will use the official demo storefront):**
1. Go to the Saleor storefront (e.g. [product page](https://demo.saleor.io/default-channel/en-US/products/abba-abba-1970-1982/))
2. Wait for the token to expire (5 minutes)
3. Do any action that will make a Graphql request (e.g. click Add to cart)
4. There is a `Maximum call stack size exceeded error` in the console and everything is broken.

If you run Performance Profiler while an error occurs, you can clearly see that the problem is in the handling of the token refresh. 

![image](https://github.com/saleor/auth-sdk/assets/10003540/a3bc778e-8fa9-4ed5-a292-3eb333da54e7)

**Comment by Jyrno42** [comment]
I added a PR that aims to fix it, at-least this seemed to work on our saleor version (based on https://github.com/saleor/react-storefront/commit/e07ccdc176bf924206ffb6ba7e2f1a6dc396d2d5 so SaleorAuthClient from it ended up in this repo).

**Comment by lephuongbg** [comment]
Can confirm that the code in PR by @Jyrno42 works. No longer getting maximum call stack error (for Chrome or Chrome-based browsers) or too much recursion for Firefox.

**Comment by pitkes22** [comment]
I have also tried the version from the #12 PR and it resolved the `Maximum call stack size exceeded error` in my project. Good job @Jyrno42 :+1:
