### ISSUE TITLE
🧠 Create an example for Saleor Auth SDK with Next.js App Router

### ISSUE THREAD

**Issue by mmiszy** [saleor/auth-sdk#16]

**Comment by ben-cook** [comment]
It would be great to gave an example with an external auth provider to go along with a Next 13 `app` router example - I'm currently struggling to integrate the two. Thank you for the hard work! 🙏

**Comment by mmiszy** [comment]
@ben-cook this is now implemented in https://github.com/saleor/auth-sdk/releases/tag/1.0.0
