### ISSUE TITLE
Warn about JWT token iss parameter mismatch

### ISSUE THREAD

**Issue by pitkes22** [saleor/auth-sdk#5]
Currently `SaleorAuthClient` checks the value of the `iss` parameter in the JWT token and [compares it with the URL](https://github.com/saleor/auth-sdk/blob/e5f31e9458fdf352ad32bb995b4b064d50930e75/src/SaleorAuthClient.ts#L60C1-L68C8) of the request. If they do not match it will not add  `Authorization` headers to the request.

I encounter this error and spent **DAYS** debugging authentification not working. It would save me a lot of time if this was documented or if there was a warning in the console that the authorization header is not added due to JWT Token issuer mismatch.

Also unrelated directly to auth-sdk but may save someone time. When I understood that the token issuer must match the request's URL, I decoded the token I got from the saleor. Turned out it pointed to `http:` insted of `https:`, and to resolve the issue I once again have to read the source code of the saleor to find that it uses a `ENABLE_SSL` enviroment variable that is conveniently NOT documented anywhere and it [decides based of it if URL should start with `http` or `https`.](https://github.com/saleor/saleor/blob/1d21b8fd1a2cd196481216ab092fb858cafdf8da/saleor/core/utils/__init__.py#L31)

**Comment by mmiszy** [comment]
Do you mind opening an issue about documenting the `ENABLE_SSL` in https://github.com/saleor/saleor-docs/issues/new ? Thanks!

We're actively working on updating the docs in this repository as we speak. We'll add a note about the `iss` field.
